# -*- coding: utf-8 -*-
"""Lab. Listas #1 FP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZpuSKqVec0Gl-2Qd4R44Nr0NIx-VTNM
"""



"""<div class="markdown-google-sans">

## <strong>Clase de listas 1</strong>
</div>

Clase de listas 1
"""

import random as rd

#1)Crear una lista vacia
L1=[]


#2)Crear una lista con 5 nombres de amigos
L2=["Nicol","Britt","Romina","Alfredo","Symond"]
#print(L2)

#3)Agregue L2 a L
#L3=L2+L1
L1.extend(L2)
#print(L3)


#4)Inserte un elemento al inicio y al final de la lista
L1.insert(0,"Liliam")
L1.append("Bolivar")


#5)Agregue un elemento en la posicion 3 de la lista L
L1.insert(3,"Emilio")


#6)Elimine el contenido de L2
L2.clear()
print(L2)

#7)Ordene alfabeticamente la lista L
L1.sort()
print(L1)

#8)Sortee un nombre de la lista
suerte=rd.choice(L1)
print(suerte)

#9) Cree un L3 que contenga las edades de las personas de L2
L3=[18,51,18,18,45,17,18,18]
print(L3)

#10) Saque máx, mín y prom de las edades de la lista L3
mas=max(L3)
mini=min(L3)
prom= sum(L3)//len(L3)
print("El máx. es: ",mas)
print("El mín. es: ",mini)
print("El prom. es: ",prom)